Spanish translation
StateOfJS/StateOfJS-2019 pull request #77
Opened 2020-02-13 22:01 UTC by wemf

<h3>User Interface</h3>

- [x] Tshirt

<h4>Demographics</h4>

- [x] Salary Ranges
- [x] Years of Experience
- [x] Company Size
- [x] Sources
- [x] CSS Proficiency
- [x] Back-end Proficiency
- [x] Job Title
- [x] Gender
- [x] Other

<h4>Features</h4>

- [x] General
- [x] Feature Overview
- [x] Features Section Overview

<h4>Tools</h4>

- [x] General
- [x] Rankings
- [x] Overview
- [x] Arrows
- [x] Quadrants
- [x] Happiness
- [x] Experience
- [x] Other Tools

<h4>Other Tools</h4>

- [x] Other Tools
- [x] Resources
- [x] Opinions
- [x] Awards

<h4>Generic</h4>

- [x] Pages
- [x] Sharing
- [x] Export
- [x] General
- [x] Partners
- [x] Charts
- [x] Other

<h3>Introductions</h3>

- [x] Introduction
- [x] Demographics
- [x] Features
- [x] Flavors
- [x] Front-end Frameworks
- [x] Data Layer
- [x] Testing
- [x] Back-end Frameworks
- [x] Mobile & Desktop
- [x] Other Tools
- [x] Resources
- [x] Opinions
- [x] Awards

<h3>Conclusions</h3>

- [x] Conclusion

2020-02-24 14:33 UTC, gemanepa requested changes

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/opinions.md
> +A veces, la mejor manera de tomar el pulso de una comunidad es simplemente tomar la iniciativa y preguntar. Desde tu opinión sobre la tasa de cambio de JavaScript, hasta las preguntas más espinosas c
_A veces, la mejor manera de tomar el pulso de una comunidad es simplemente tomar la iniciativa y preguntar. Desde tu opinión sobre la ~~tasa~~ **velocidad** de cambio de JavaScript, ~~hasta las~~ **a** preguntas más espinosas como si JavaScript se está moviendo en la dirección correcta, ¡~~finalmente se tuvo~~ **Finalmente tuviste**  la oportunidad de decirnos exactamente lo que está ~~pensando~~ **en tu mente**!_

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/other-tools.md
> +Siempre necesita un editor de texto para codificar, pero el proceso de escribir JavaScript también se basa en navegadores y herramientas de desarrollo en mayor medida que probablemente cualquier otro
_Siempre necesita**s** un editor de texto para codificar, pero el proceso de escribir JavaScript también ~~se basa en~~ **depende de** navegadores y herramientas de desarrollo en mayor medida que probablemente cualquier otro ~~idioma~~ **lenguaje**._

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/overview.md
> +Antes de profundizar en los detalles, tomemos un momento para tener una visión general del ecosistema JavaScript en el 2019, cortesía de la talentosa [Amelia Wattenberger](https://wattenberger.com/),
_¡~~n~~**N**uestra invitada experta en visualización de datos!_

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/conclusions/conclusion.md
> +¿Sabes cómo a veces comienzas a ajustar algunas líneas de código aquí y allá, luego te das cuenta de que un par de funciones podrían ser refactorizadas, y luego, una cosa que lleva a otra, te encuent
_te encuentras unos días más tarde en el proceso de configurar ~~una nueva con~~ un nuevo stack completo con una base de datos y API GraphQL?_

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/conclusions/conclusion.md
> +Esto es lo que nos pasó este año. Y aunque resultó en algunas noches estresantes mientras intentábamos concluir esto y publicar los resultados del Estado de JavaScript 2019, bueno en el 2019; También
Y aunque resultó en algunas noches estresantes mientras intentábamos concluir esto y publicar los resultados del Estado de JavaScript 2019 ~~, bueno en el~~ **en, bueno,** 2019; También significa que ahora tenemos un stack mucho más potente y flexible para recopilar y analizar datos en ~~el futuro~~ **adelante**.

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/introduction.md
> +<span class="first-letter">N</span>osotros estábamos bastante seguros de que el 2018 sería la última vez que realizariamos esta encuesta. Después de todo, el ecosistema de JavaScript no puede seguir
`<span class="first-letter">E</span>stábamos bastante seguros de que el 2018...`

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/introduction.md
> +We also borrowed a couple new visualisations from the State of JS's sister survey, the [State of CSS](https://2019.stateofcss.com/). We recommend checking it out if you haven’t done so yet!
Line 13 should be deleted :)

2020-02-24 14:33 UTC, gemanepa commented on src/translations/es-ES/introductions/introduction.md
> +Pero, ¿qué sabes? ¡resulta que JavaScript todavía no ha cambiado completamente! Y así, después de que más de 21,717 personas respondieron la encuesta de este año, tuvimos que desenterrar nuestros com
~~Pero, ¿qué sabes?~~ **Pero quien se lo habria imaginado**

2020-03-07 16:44 UTC, arodrigueze0215 commented on src/translations/es-ES/conclusions/conclusion.md
> +Esto es lo que nos pasó este año. Y aunque resultó en algunas noches estresantes mientras intentábamos concluir esto y publicar los resultados del Estado de JavaScript 2019, bueno en el 2019; También
_También significa que ahora tenemos un stack mucho más potente y flexible para recopilar y analizar datos en el ~futuro~ adelante._

Pienso que __*futuro*__ no está mal. No se necesitaría traducir textualmente.

2020-10-08 00:29 UTC, SachaG commented
First of all, thanks again for your help with translating the 2019 edition of the survey. Also, we've started our translation efforts for this year, and this time we'll try to translate the survey questions as well! 

More info here: https://github.com/StateOfJS/StateOfCSS-2020/issues/2

2020-10-11 07:20 UTC, nahumzs commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
el sitio hace uso de de IBM PLEX MONO you made use of a font family you dont config you site with a font-family there is not knob to turn on/ turn off IBM. IMHO.

2020-10-11 07:21 UTC, nahumzs commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
retroalimentoación no realimentación, maybe a typo?

2020-10-12 23:23 UTC, alebrozzoamz commented on src/translations/es-ES/introductions/opinions.md
> +A veces, la mejor manera de tomar el pulso de una comunidad es simplemente tomar la iniciativa y preguntar. Desde tu opinión sobre la tasa de cambio de JavaScript, hasta las preguntas más espinosas c
A veces, la mejor manera de tomar el pulso de una comunidad es simplemente tomar la iniciativa y preguntar. Desde tu opinión sobre la ~tasa~ *velocidad* de cambio de JavaScript, hasta las preguntas más espinosas como si JavaScript se está moviendo en la dirección correcta, ¡finalmente ~se tuvo~ *tienes* la oportunidad de decirnos exactamente lo que ~está pensando~ *opinas*!

2020-10-13 02:22 UTC, jmz7v commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
Retroalimentación es una palabra con la que estoy más familiarizado. ¿Saben si hay diferencia perceptual entre Español de LATAM y de España?

2020-10-13 03:05 UTC, nahumzs commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
si bien realimentación y retroalimentación pueder ser sumamente similares, (https://dle.rae.es/retroalimentaci%C3%B3n)[retroalimentación] a mí parecer es mucho más cercana a lo que se quiere comunicar aquí:

> 1. f. Biol. y Tecnol. Retorno de parte de la energía o de la información de salida de un circuito o un sistema a su entrada.

2020-10-13 03:18 UTC, alebrozzoamz commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
Qué dice el documento original? Tal vez se pueda usar una palabra menos técnica que siga el espíritu de lo que se quiere decir en inglés

2020-10-13 03:43 UTC, nahumzs commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
> The site is set in IBM Plex Mono. Questions? Feedback? [Get in touch!](mailto:hello@stateofjs.com)
--

I think we are looking for the word **"sugerencias"** :D

2020-10-13 03:46 UTC, alebrozzoamz commented on src/translations/es-ES/introductions/introduction.md
> +¡Y ahora, veamos qué ha estado haciendo JavaScript este año!
estoy de acuerdo

2020-10-20 14:56 UTC, smarquez-dev commented on src/translations/es-ES/introductions/introduction.md
> +Debido a que todas las preguntas de la encuesta podrían saltarse, algunas preguntas terminaron con menos respuestas que otras. Por lo tanto, hemos agregado un pequeño indicador de gráfico circular a
Debido a que todas las preguntas de la encuesta podrían podían saltarse, algunas preguntas terminaron con menos respuestas que otras. Por lo tanto, hemos ~~agregado~~ añadido un pequeño indicador de gráfico circular a cada pregunta para informarte qué proporción del total de encuestados respondió.

2023-06-11 16:01 UTC, closed without merging